### ISSUE TITLE
Possivel erro na nomenclatura

### ISSUE THREAD

**Issue by idylicaro** [marcosdosea/biblioteca-es#7]
Acredito que há um possível error na nomenclatura de dois testes.

Em código o endpoint que é POST ele tem dois parâmetros, e no teste ta sendo passado 2 parâmetros para o teste que cita o endpoint que é GET.
---
![image](https://user-images.githubusercontent.com/45442467/141642637-0107e3b9-d0c7-4266-b69a-2e88013212be.png)
---
![image](https://user-images.githubusercontent.com/45442467/141642686-ffd77c50-d707-4491-a95a-c135d293a5c5.png)

**Comment by marcosdosea** [comment]
Excelente @idylicaro . Obrigado!
